webRunes/Chess-WRIO-Game

server.js
Make little refactoring:
- Removes unnecessary blocks of code.
- Substitute use of series method with waterfall to call methods one after another.
- Move query to the constant.
- Add use of moment.js lib to work with date and time.
=> Change query to search only twits with phrases "#chess start" and "start #chess"

appData/index.js, appData/utils.js, package.json, server.js, titter/index.js, titter/titterClient.js
=> Integrate Chess app with MySQL database to save since_id between restarts of the server.

appData/index.js, appData/utils.js, chess_engine/chessEngine.js, chess_engine/chessEngineClient.js, package.json, server.js, titter/index.js, titter/titterClient.js
https://github.com/webRunes/Chess-WRIO-Game/issues/11
=> Game start #11

config.json.default
https://github.com/webRunes/WRIO-InternetOS/issues/224
=> Added config.json.default

config.json.default
https://github.com/webRunes/WRIO-InternetOS/issues/224
=> Added comments to twitterLogin section

appData/utils.js, chess_engine/chessEngineClient.js, package.json
https://github.com/webRunes/Login-WRIO-App/issues/129
=> Mongodb transition

app.js, chess_engine/chessEngineClient.js, persistent/controller.js
Moving visualization, color control, game over control
=> Chess move

app.js, chess_engine/chessboardGenerator.js, config.json.default, persistent/controller.js, persistent/route.js, utils/titterClient.js
Transfer chessboard image inside request, remove image after that sent
to twitter, servers url config fix.
=> Image file storing

app.js, appData/index.js, appData/utils.js, server.js
Add support any word order. Remove multiple db connection. App data
transfer fix.
=> Add support any word order

chess_engine/chessboardGenerator.js, server.js
https://github.com/webRunes/Titter-WRIO-App/issues/185,
circle server restart problem fix
=> Update Titter signature text

app.js
=> Tweets filter

.travis.yml
https://github.com/webRunes/Chess-WRIO-Game/issues/40
=>  S3 #40: configured chess to deploy on S3 dev bucket

.travis.yml
https://github.com/webRunes/Chess-WRIO-Game/issues/40
=>  S3 #40: configured chess to deploy on S3 prod bucket

persistent/route.js, robots.txt
=> Add robots filter

persistent/controller.js, persistent/route.js
=> Add invite control

persistent/controller.js, persistent/route.js
=> Add UploadMedia response log

persistent/controller.js
=> Parsing error fix

app.js
=> Opponent name parsing fix

utils/access.js
=> Opponent name save fix

app.js, chess_engine/chessEngineClient.js, chess_engine/chessboardGenerator.js, persistent/controller.js, persistent/route.js, server.js, utils/titterClient.js
https://github.com/webRunes/Chess-WRIO-Game/issues/69
=> Update notifications & features #69

persistent/controller.js
https://github.com/webRunes/Chess-WRIO-Game/issues/84
=> #chess end issue #84

persistent/controller.js
https://github.com/webRunes/Chess-WRIO-Game/issues/85
=> Start game #85 (hotfix)

chess_engine/chessEngineClient.js, chess_engine/main.js, persistent/controller.js
https://github.com/webRunes/Chess-WRIO-Game/issues/85
=> Start game #85

src/client/js/start.js, src/server/persistent/controller.js
=> Temporary fix

gulpfile.js, package.json, server.js, src/client/views/start.htm, src/index.js, src/server/app.js, src/server/appData/index.js, src/server/appData/utils.js, src/server/persistent/controller.js, src/server/persistent/route.js, src/server/utils/access.js, src/server/utils/db.js, src/server/utils/secure.js, src/server/utils/titterClient.js, src/server/utils/twitterClient.js, src/server/wrio_nconf.js, src/server/wriologin.js
https://github.com/webRunes/Chess-WRIO-Game/issues/121
change tabs to spaces
=> https #121

readme.md, src/client/js/start.js
=> Callback fix

src/client/js/start.js, src/index.js, src/server/persistent/controller.js, src/server/wriologin.js
Update chess api for working with new widget
=> Chess widget

src/index.js, src/server/persistent/controller.js, src/server/persistent/route.js
Change checking current user by wriodID instead titterID
=> Fix checking current user

src/server/app.js, src/server/persistent/controller.js, src/server/persistent/route.js
fixed controller errors
fixed missed dependencies(lodash module)
=> Chess controller fix

package-lock.json, package.json
=> Review vulnerable dependencies #1293
